import "./globals.css";
import NavBar from "components/navbar";
import { CategoryColoursProvider } from "@/app/context/CategoryContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <CategoryColoursProvider>
          <NavBar />
          {children}
        </CategoryColoursProvider>
      </body>
    </html>
  );
}
